Ner and pos
cpdoc/test pull request #4
Opened 2021-02-24 18:35 UTC by igorcj

DHBB_JSON pack update and Conllu app development.

2021-02-24 18:53 UTC, arademaker requested changes
fiz comentários para correções.

2021-02-24 18:53 UTC, arademaker commented on app/ConlluProcess.hs
> +-- Provavelmente não precisarei de todos esses imports. Tirarei quando o codigo estiver pronto
fez isso?

2021-02-24 18:53 UTC, arademaker commented on package.yaml
> +- bytestring
não precisamos disso, o pacote já tem esta dependencia:

```
% stack ls dependencies | grep bytestring
/Users/ar/work/cpdoc/test/test.cabal was modified manually. Ignoring /Users/ar/work/cpdoc/test/package.yaml in favor of the cabal file.
If you want to use the package.yaml file instead of the cabal file,
then please delete the cabal file.
bytestring 0.10.12.0
```

2021-02-24 18:53 UTC, arademaker commented on src/DHBB_JSON.hs
> +module DHBB_JSON where
Melhor algo como `NLUJson` (NLU é o nome do serviço da IBM que gera aquele JSON.

2021-02-24 18:53 UTC, arademaker commented on app/ConlluProcess.hs
> +range :: ReadP Range -- Range parser
Talvez aqui saia mais simplesmente com algo como fiz em https://github.com/cpdoc/test/blob/main/app/Sentence.hs#L56.

2021-02-24 18:53 UTC, arademaker commented on app/ConlluProcess.hs
> +
remover comentários desnecessários de caminhos antigos.

2021-02-27 11:51 UTC, igorcj commented on app/ConlluProcess.hs
> +-- Provavelmente não precisarei de todos esses imports. Tirarei quando o codigo estiver pronto
Ainda não acabei esse executável, por isso mantive imports e funções comentadas. No processo posso puxar alguns deles de volta, como ja fiz anteriormente. Quando o executavel estiver completamente funcional reduzirei ao essencial.

2021-02-27 21:35 UTC, igorcj commented
Agora o executável conllu ja conta com o modulo de mergear os json  nos conllu funcionando. Irei incluir a analise no memso arquivo, usando o argparse que ja montei.

2021-02-27 22:47 UTC, arademaker commented
Ok. Aguardo para testar e aceitar no master

2021-03-02 21:27 UTC, merged